name: hive_flutter_example
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_riverpod: ^2.4.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.9.0   
  flutter_localization: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  freezed: ^2.3.2
  json_serializable: ^6.9.5   

flutter:
  uses-material-design: true

  fonts:
    - family: MaterialIcons
